// Generated by LiveScript 1.5.0
(function(){
  var jsonfile, applications, filtered, i$, len$, x, email, applicant_name, first_name, last_name, ref$;
  jsonfile = require('jsonfile');
  applications = jsonfile.readFileSync('applications.json');
  filtered = [];
  for (i$ = 0, len$ = applications.length; i$ < len$; ++i$) {
    x = applications[i$];
    if (x.title.indexOf('HabitLab') === -1) {
      continue;
    }
    if (x.year === 'Freshman') {
      continue;
    }
    if (parseFloat(x.gpa) < 3.6) {
      continue;
    }
    filtered.push(x);
  }
  for (i$ = 0, len$ = filtered.length; i$ < len$; ++i$) {
    x = filtered[i$];
    email = x.email, applicant_name = x.applicant_name;
    first_name = applicant_name.split(' ')[0];
    last_name = (ref$ = applicant_name.split(' '))[ref$.length - 1];
    console.log(first_name + "\t" + last_name + "\t" + email);
  }
}).call(this);
